### PR TITLE
Updated KOB details and status in line with Public utility creation 

### PR DESCRIPTION
**Pull request by panickervinod**
Updated KOB details and status in line with Public utility creation

### CODE REVIEW

**Comment by vinomaster** [comment]
I propose we hold on merging this PR until this utility candidate is presented to the UFWG.

I am not convinced that KOB is an instance of a Public Identity Utility. As per its own definition, it is a  Verifiable Organization Network(VON) which implies to me that it is an instance of an Ecosystem.... May be better associated with EFWG.

**Comment by panickervinod** [comment]
Sure Dan, We had discussed listing KOB initiative in the co-chair connect yesterday.

I will give  an overview of the same in today’s APAC call (again).  We had discussed listing KOB initiative in the co-chair connect yesterday.

KOB is conceptualized as a Public utility , it will have a  Trust Network  of its own, Wallet App , agents, VCR  , governance frameworks and all other components required for it to function.

Regards
Vinod.


[http://marketing.wiprodigital.com/apps/wipro-esig/assets/images/logo-01.png]<http://www.wipro.com/>
Vinod Panicker
Chief Architect- Cybersecurity,Open source,Blockchain
Distinguish Member Technical Staff- Senior Member
M: +91 99958 23346<tel:+91%2099958%2023346>
in/vinodpanicker<https://www.linkedin.com/in/vinodpanicker>
Wipro Limited
Learning Center, 2nd Floor, Infopark, SEZ, Kusumagiri, P.O. Kochi 682030

**Comment by panickervinod** [comment]
Vinod Panicker (CRS) would like to recall the message, "[trustoverip/utility-foundry-wg] Updated KOB details and status in line with Public utility creation  (#24)".
'The information contained in this electronic message and any attachments to this message are intended for the exclusive use of the addressee(s) and may contain proprietary, confidential or privileged information. If you are not the intended recipient, you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately and destroy all copies of this message and any attachments. WARNING: Computer viruses can be transmitted via email. The recipient should check this email and any attachments for the presence of viruses. The company accepts no liability for any damage caused by any virus transmitted by this email. www.wipro.com'

**Comment by panickervinod** [comment]
Sure Dan, We had discussed listing KOB initiative in the co-chair connect yesterday.

I will give  an overview of the same in today's APAC call (again).

KOB is conceptualized as a Public utility , it will have a  Trust Network  of its own, Wallet App , agents, VCR  , governance frameworks and all other components required for it to function.

Regards
Vinod.


[http://marketing.wiprodigital.com/apps/wipro-esig/assets/images/logo-01.png]<https://apc01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.wipro.com%2F&data=04%7C01%7Cvinod.panicker%40wipro.com%7C4f8e46e0d93641c8489c08d8903539c0%7C258ac4e4146a411e9dc879a9e12fd6da%7C1%7C0%7C637417905568933416%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=OEeS%2FZdl2Kmce2rNoy6ipcGXvM4S7bGGletLwiQ2JTE%3D&reserved=0>
Vinod Panicker
Chief Architect- Cybersecurity,Open source,Blockchain
Distinguish Member Technical Staff- Senior Member
M: +91 99958 23346<tel:+91%2099958%2023346>
in/vinodpanicker<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.linkedin.com%2Fin%2Fvinodpanicker&data=04%7C01%7Cvinod.panicker%40wipro.com%7C4f8e46e0d93641c8489c08d8903539c0%7C258ac4e4146a411e9dc879a9e12fd6da%7C1%7C0%7C637417905568943408%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=qRp%2F1k%2BI6heRBporYlTDdtJfpu4vkWRm7T5%2BmI8zoJU%3D&reserved=0>
Wipro Limited
Learning Center, 2nd Floor, Infopark, SEZ, Kusumagiri, P.O. Kochi 682030

**Comment by vinomaster** [comment]
@panickervinod So is it possible then to learn about the trust network it will govern and use? We are trying to separate the layers here Vinod. If you have convened a set of stakeholders associated with the City of Kochi then you should be able to convey this and help us understand how this utility will operate. For example, Is it decentralized or centralized?  It would seem that [your own documentation](https://thekochiorgbook.github.io/KochiOrgBook/community_initiative/) points to the use of a decentralized public identity utility  -- namely the Sovrin Network. That is perfectly fine and great news. But it implies that the KOB VON **is not a public identity utility** nor does it have a uniquely new component effort underway that would represent such a utility.

**Comment by panickervinod** [comment]
@vinomaster  Thanks for spotting the issue with the documentation, It is currently WIP and the document image reference currently point to the technology demonstrator. It will get updated shortly :) You will not find Sovrin in there..

We will update the details on the trust network for KOB, the key stakeholders how it would operate in the next APAC utility call.

**Comment by vinomaster** [comment]
This PR was discussed at the UFWG meeting today. It has been decided that we need more information and that this PR is premature and should be cancelled and resubmitted later. 

Please answer these questions](https://github.com/trustoverip/utility-foundry-wg/blob/master/workflow/UTILITY_WORKFLOW.md#convene) PLUS:
1. Who is the Public Utility Convener?
2. Who are the stakeholders sponsoring the work?

**Comment by panickervinod** [comment]
@vinomaster  The public utility convener is the KOB consortium comprising of Wipro, CUSAT and KBA. The stakeholders sponsoring the work are the same.

**Comment by vinomaster** [comment]
@panickervinod 

A **Public Identity Utility (PIU)** is a distinct system of domain specific ledgers operated by decentralized peer nodes and associated with a DID Namespace. The DID Ledger, is governed by an independent governing body and its own governance framework. 

We are trying to follow a process and thanks for your patience as we evolve the process. We want to make sure listed utilities represent actual utility projects.

When you answer [these questions](https://github.com/trustoverip/utility-foundry-wg/blob/master/workflow/UTILITY_WORKFLOW.md#convene) and follow [these instructions](https://github.com/trustoverip/utility-foundry-wg/blob/master/workflow/UTILITY_WORKFLOW.md#utility-projects) we can evaluate the KOB submission. 

I urge you to consider the fact that to-date KOB has been presented as a VON-like system -- which positions it as an **ecosystem project**.  If KOB is comprised of a dedicated public identity utility component then you should focus your submission on that component. If work on that PIU component has not yet achieved *convene stage* then pls holdoff your submission.

The [Workflow Story](https://github.com/trustoverip/utility-foundry-wg/blob/master/workflow/UTILITY_WORKFLOW.md#utility-projects) can address the broader KOB system BUT the goal of the story is to describe the journey for the creation and implementation of the PIU Project itself. 

If this is still unclear, please schedule time to discuss.

**Comment by panickervinod** [comment]
@vinomaster  Okay Dan will schedule a call to discuss. Please can you share the link to the other submissions as well.

**Comment by vinomaster** [comment]
The [UFWG decided on 19-Jan-2021](https://wiki.trustoverip.org/display/HOME/2021-01-19+Meeting+Page) to CLOSE this PR and request a resubmission when the KOB Utility Project is in a better position of readiness.

**Pull request closed without merging**
